import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/prisma";
import nodemailer from "nodemailer";

export async function POST(req: NextRequest) {
  try {
    const { pdfBase64, to, subject, filename, patientName, bodyText } = await req.json();

    if (!pdfBase64 || !to || !subject) {
      return NextResponse.json({ ok: false, error: "Faltan campos requeridos." }, { status: 400 });
    }

    // Decode base64 PDF generated by the browser
    const pdfBuffer = Buffer.from(pdfBase64, "base64");

    // Get SMTP config
    const rows = await prisma.clinicConfig.findMany();
    const cfg  = Object.fromEntries(rows.map((r) => [r.key, r.value]));
    const host   = process.env.SMTP_HOST   || cfg.smtp_host;
    const port   = parseInt(process.env.SMTP_PORT   || cfg.smtp_port   || "465");
    const secure = (process.env.SMTP_SECURE || cfg.smtp_secure || "true") === "true";
    const user   = process.env.SMTP_USER   || cfg.smtp_user;
    const pass   = process.env.SMTP_PASS   || cfg.smtp_pass;
    const name   = cfg.clinic_name ?? "Clínica Magna";

    if (!host || !user || !pass) {
      return NextResponse.json(
        { ok: false, error: "Email no configurado. Configure SMTP en Ajustes." },
        { status: 500 }
      );
    }

    const safeFilename = (filename || "documento").replace(/[^a-z0-9_\-]/gi, "_");
    const emailText    = bodyText || `Estimado/a ${patientName || "paciente"}, adjuntamos su documento. Saludos, ${name}.`;

    try {
      const transporter = nodemailer.createTransport({ host, port, secure, auth: { user, pass } });
      await transporter.sendMail({
        from: `"${name}" <${user}>`,
        to,
        subject,
        text: emailText,
        attachments: [
          {
            filename: `${safeFilename}.pdf`,
            content:  pdfBuffer,
            contentType: "application/pdf",
          },
        ],
      });
      return NextResponse.json({ ok: true });
    } catch (e) {
      return NextResponse.json({ ok: false, error: `Error enviando email: ${String(e)}` }, { status: 500 });
    }
  } catch (e) {
    return NextResponse.json({ ok: false, error: String(e) }, { status: 500 });
  }
}
